image_width: 1920
image_height: 1080
camera_name: camera_forward
camera_matrix:
  rows: 3
  cols: 3
  data: [1198.7009 ,    0.     ,  930.39216,
            0.     , 1200.66411,  533.75755,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.339423, 0.093590, 0.001272, -0.000781, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 872.07351,    0.     ,  907.5403 ,    0.     ,
            0.     , 1110.46217,  534.01337,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
