s57_grids:
  map_frame: izzy/map

  robot:
    frame_id: izzy/base_link

udp_bridge/remotes:
  operator:
    connections:
      default:
        topics:
          oak_rgb: {source: sensors/cameras/oak/rgb/image_raw/compressed, period: 0.25}
          oak_rgb_info: {source: sensors/cameras/oak/rgb/camera_info}

